---
- name: Install base packages, deactivate automatic upgrades
  hosts: all
  tasks:
    - import_tasks: tasks/deactivate_unattented_ugrades.yml
      when: ansible_os_family == "Debian"
    - name: install base packages
      package:
        name: "{{ base_packages }}"
        state: present
