---

- name: install debconf utils
  apt:
    name:
      - debconf
      - debconf-utils
    state: present

- name: deactivate unattended upgrades
  debconf:
    name: unattended-upgrades
    question: unattended-upgrades/enable_auto_updates
    value: false
    vtype: boolean
